//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class education
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string subtitle1 { get; set; }
        public string subtitle2 { get; set; }
        public string GNO { get; set; }
        public string date { get; set; }
    }
}
