//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class resumeEntities : DbContext
    {
        public resumeEntities()
            : base("name=resumeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<about> about { get; set; }
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<certificate> certificate { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<education> education { get; set; }
        public virtual DbSet<experience> experience { get; set; }
        public virtual DbSet<hobby> hobby { get; set; }
        public virtual DbSet<skill> skill { get; set; }
        public virtual DbSet<socialmedia> socialmedia { get; set; }
    }
}
